x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.11.0
    environment:
      SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    logging: *default-logging

  proxy:
    image: lblod/api-proxy-service:feature-plugin-support
    environment:
      API_URL: "<IPDC ConceptSnapshot LDES feed endpoint>"
    volumes:
      - ./config/proxy/:/config/